name: Discogs client library build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branchs: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build
        run: make build
